import "./globals.css";
import Menu from "@/app/components/Menu";
import Contact from "./components/Contact";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className="">
        <Menu />
          <main className="max-w-6xl mx-auto py-10">
          {children}
          </main>
        <Contact />
      </body>
    </html>
  );
}
